name: Add Icon

on:
  push:
    branches:
      - main

jobs:
  add_icon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add Icon
        uses: actions/upload-artifact@v2
        with:
          name: icon
          path: ./icon.png
